### ISSUE TITLE
Mable's Fables

### ISSUE THREAD

**Issue by stefandiiorio** [Callbam/digital#3]
Did an update to the site's press section. On squarespace.

**Comment by stefandiiorio** [comment]
Updated from Rachel

- [ ] • making the logo the same size as the above one
- [ ] • making the "Highlighted on..." text bold like the above one
- [ ] • making the quote below it regular and italicized
- [ ] • making the width of the text equal in length

**Comment by scmwalsh** [comment]
Make required updates to the KJ Rankin website;
http://www.kjrankin.com/press/

**Comment by scmwalsh** [comment]
Fixed minor grammatical errors.
